### ISSUE TITLE
Use replace for vendor files

### ISSUE THREAD

**Issue by vvs-code** [andybluntish/ember-cli-replace#3]
Can you show example how to configure addon to replace patterns in vendor files ( some addon for example )

I try to use addon's namespace, absolute path but it doesn't work.

**Comment by andybluntish** [comment]
Hi Vasiliy,

The replacement happens in the `postprocessTree` hook, so its essentially running once the files have already been processed. If you want to replace a value in a vendor file, you'll need to add `assets/vendor.js` to the files array:

```js
var app = new EmberApp({
  replace: {
    files: [
      'assets/vendor.js'
    ],
    patterns: [{
      match: 'foo',
      replacement: 'bar'
    }],
  }
});
```
This should also cover most addon files too, but if not, you can also try adding `assets/[app-name].js` too.

Hope that helps.
